### ISSUE TITLE
`ParentDispatcherChangedDisposable.Dispose()` thread safety

### ISSUE THREAD

**Issue by dlbd** [nventive/Chinook.DynamicMvvm#87]
`ParentDispatcherChangedDisposable.Dispose()` can throw a `NullReferenceException` if called twice quickly.

This code ( https://github.com/nventive/Chinook.DynamicMvvm/blob/1d312d1649c1be64324faf7a738c5f6852b50fd8/src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Children.cs#L175C18-L175C18 ) is not thread-safe:
```c#
			public void Dispose()
			{
				_parentViewModel.DispatcherChanged -= OnParentDispatcherChanged;
				_parentViewModel = null;
				_childViewModel = null;
			}
```
`_parentViewModel` should probably be copied to a local variable and null-checked before unsubscribing.

Stack trace (posted as an image, as `($exception).StackTrace` was truncated):

![image](https://github.com/nventive/Chinook.DynamicMvvm/assets/1613158/c1e5f8f1-32d4-40b3-ac56-a0076388eb21)

## Expected Behavior

`NullReferenceException` is not thrown.

## Actual Behavior

`NullReferenceException` is sometimes thrown.

## Steps to Reproduce the Problem

This is a bit difficult to reliably reproduce. It appears to happen when list view's contents are changing quickly, and the user navigates to another page.

## Specifications

- Version: 1.2.0, also 1.2.1
- Platform: Uno WinUI, possibly iOS and Android
- Subsystem: Chinook.DynamicMvvm

**Comment by jeanplevesque** [comment]
Fixed in [1.2.2](https://www.nuget.org/packages/Chinook.DynamicMvvm.Abstractions/1.2.2).
