### ISSUE TITLE
Add GetFromDeactivatableObservable<T> overload with Func<IObservable<T>>

### ISSUE THREAD

**Issue by dlbd** [nventive/Chinook.DynamicMvvm#89]
Using`GetFromDeactivatableObservable` may cause an observable to be recreated on every property access (depending on what `GetComplicatedObservable()` does in the example below).

```c#
public int Something => this.GetFromDeactivatableObservable(GetComplicatedObservable());
```

Please provide an overload that takes the observable as a lambda, like this:

```c#
public int Something => this.GetFromDeactivatableObservable(() => GetComplicatedObservable());
```

**Comment by jeanplevesque** [comment]
Implemented in [1.4.0](https://www.nuget.org/packages/Chinook.DynamicMvvm/1.4.0).
